# Configuração de análise estática para o projeto TagBean
# Este arquivo configura regras de lint e warnings do Dart Analyzer

include: package:flutter_lints/flutter.yaml

analyzer:
  # Habilita análise estrita
  language:
    strict-casts: true
    strict-raw-types: true
  
  # Exclui arquivos gerados automaticamente
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "lib/generated/**"
    - "build/**"
    - ".dart_tool/**"
  
  # Configuração de severidade dos erros - foco em detectar código morto
  errors:
    # Erros que devem permanecer como erro
    invalid_assignment: error
    missing_return: error
    
    # Código morto e variáveis não usadas - warnings importantes
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
    unused_element: warning
    unused_field: warning
    unused_element_parameter: warning
    
    # Deprecations e casts desnecessários
    deprecated_member_use: info
    deprecated_member_use_from_same_package: info
    unnecessary_cast: warning
    
    # Dead null aware expression (pode indicar código que precisa de revisão)
    dead_null_aware_expression: warning
    
    # Imports
    unnecessary_import: warning
    
    # Default clause unreachable
    unreachable_switch_default: warning

linter:
  rules:
    # Regras de estilo habilitadas
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: false
    avoid_print: false  # Desabilitado para debugging
    
    # Regras de documentação (desabilitadas por enquanto)
    public_member_api_docs: false
    
    # Regras de nomenclatura
    constant_identifier_names: true
    non_constant_identifier_names: true
    
    # Regras de código limpo
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    require_trailing_commas: false
    
    # Regras de segurança
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true

# Dart Code Metrics - detecção avançada de código morto e métricas
dart_code_metrics:
  # Detectar código morto
  rules:
    - no-unused-parameter
    - no-unused-members-in-classes
    - no-unused-files
    - prefer-static-class
    - no-empty-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - prefer-conditional-expressions
    - avoid-redundant-async
    - avoid-unused-parameters

  # Métricas de qualidade
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
    source-lines-of-code: 50
    maintainability-index: 50
    number-of-methods: 10
    weight-of-class: 0.33
    
  # Análise de arquivos
  metrics-exclude:
    - test/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    
  # Reportar widgets não usados
  anti-patterns:
    - long-method
    - long-parameter-list
