# -*- coding: utf-8 -*-
"""
Script simples para corrigir palavras com encoding corrompido
Substitui apenas palavras INTEIRAS (não variáveis)
"""

import os
import re
from pathlib import Path

SEARCH_PATH = r"D:\tagbean\frontend\lib"

# Dicionário de palavras corrompidas -> palavras corretas
PALAVRAS = {
    # ============================================
    # PALAVRAS COM ACENTOS REMOVIDOS (tipo 2)
    # ============================================
    
    # Ã -> á (acentos removidos)
    'Usuarios': 'Usuários',
    'usuarios': 'usuários',
    'Usurio': 'Usuário',
    'usurio': 'usuário',
    'Configuraes': 'Configurações',
    'configuraes': 'configurações',
    'Configurao': 'Configuração',
    'configurao': 'configuração',
    'Importao': 'Importação',
    'importao': 'importação',
    'Importaes': 'Importações',
    'importaes': 'importações',
    'Exportao': 'Exportação',
    'exportao': 'exportação',
    'Exportaes': 'Exportações',
    'exportaes': 'exportações',
    'Sincronizao': 'Sincronização',
    'sincronizao': 'sincronização',
    'Operao': 'Operação',
    'operao': 'operação',
    'Operaes': 'Operações',
    'operaes': 'operações',
    'Aes': 'Ações',
    'aes': 'ações',
    'Ao': 'Ação',
    'Informao': 'Informação',
    'informao': 'informação',
    'Informaes': 'Informações',
    'informaes': 'informações',
    'Histrico': 'Histórico',
    'histrico': 'histórico',
    'Histria': 'História',
    'histria': 'história',
    'Mdulo': 'Módulo',
    'mdulo': 'módulo',
    'Mdulos': 'Módulos',
    'mdulos': 'módulos',
    'ltima': 'Última',
    'ltimo': 'Último',
    'Rpidas': 'Rápidas',
    'rpidas': 'rápidas',
    'Rpido': 'Rápido',
    'rpido': 'rápido',
    'Preo': 'Preço',
    'preo': 'preço',
    'Preos': 'Preços',
    'preos': 'preços',
    'Reduo': 'Redução',
    'reduo': 'redução',
    'Redues': 'Reduções',
    'redues': 'reduções',
    'Descrio': 'Descrição',
    'descrio': 'descrição',
    'Posio': 'Posição',
    'posio': 'posição',
    'Posies': 'Posições',
    'posies': 'posições',
    'Sugesto': 'Sugestão',
    'sugesto': 'sugestão',
    'Sugestes': 'Sugestões',
    'sugestes': 'sugestões',
    'Notificao': 'Notificação',
    'notificao': 'notificação',
    'Notificaes': 'Notificações',
    'notificaes': 'notificações',
    'Conexo': 'Conexão',
    'conexo': 'conexão',
    'Conexes': 'Conexões',
    'conexes': 'conexões',
    'Aplicao': 'Aplicação',
    'aplicao': 'aplicação',
    'Aplicaes': 'Aplicações',
    'aplicaes': 'aplicações',
    'Soluo': 'Solução',
    'soluo': 'solução',
    'Solues': 'Soluções',
    'solues': 'soluções',
    'Validao': 'Validação',
    'validao': 'validação',
    'Validaes': 'Validações',
    'validaes': 'validações',
    'Integrao': 'Integração',
    'integrao': 'integração',
    'Integraes': 'Integrações',
    'integraes': 'integrações',
    'Autenticao': 'Autenticação',
    'autenticao': 'autenticação',
    'Atualizao': 'Atualização',
    'atualizao': 'atualização',
    'Atualizaes': 'Atualizações',
    'atualizaes': 'atualizações',
    'Localizao': 'Localização',
    'localizao': 'localização',
    'Navegao': 'Navegação',
    'navegao': 'navegação',
    'Visualizao': 'Visualização',
    'visualizao': 'visualização',
    'Exibio': 'Exibição',
    'exibio': 'exibição',
    'Seleo': 'Seleção',
    'seleo': 'seleção',
    'Selees': 'Seleções',
    'selees': 'seleções',
    'Edio': 'Edição',
    'edio': 'edição',
    'Edies': 'Edições',
    'edies': 'edições',
    'Excluso': 'Exclusão',
    'excluso': 'exclusão',
    'Criao': 'Criação',
    'criao': 'criação',
    'Alterao': 'Alteração',
    'alterao': 'alteração',
    'Alteraes': 'Alterações',
    'alteraes': 'alterações',
    'Concluso': 'Conclusão',
    'concluso': 'conclusão',
    'Incluso': 'Inclusão',
    'incluso': 'inclusão',
    'Remoo': 'Remoção',
    'remoo': 'remoção',
    'Exceo': 'Exceção',
    'exceo': 'exceção',
    'Excees': 'Exceções',
    'excees': 'exceções',
    'Situao': 'Situação',
    'situao': 'situação',
    'Situaes': 'Situações',
    'situaes': 'situações',
    'Condio': 'Condição',
    'condio': 'condição',
    'Condies': 'Condições',
    'condies': 'condições',
    'Funo': 'Função',
    'funo': 'função',
    'Funes': 'Funções',
    'funes': 'funções',
    'Verso': 'Versão',
    'verso': 'versão',
    'Verses': 'Versões',
    'verses': 'versões',
    'Sesso': 'Sessão',
    'sesso': 'sessão',
    'Sesses': 'Sessões',
    'sesses': 'sessões',
    'Permisso': 'Permissão',
    'permisso': 'permissão',
    'Permisses': 'Permissões',
    'permisses': 'permissões',
    'Transao': 'Transação',
    'transao': 'transação',
    'Transaes': 'Transações',
    'transaes': 'transações',
    'Promocao': 'Promoção',
    'promocao': 'promoção',
    'Promocoes': 'Promoções',
    'promocoes': 'promoções',
    'Promoo': 'Promoção',
    'promoo': 'promoção',
    'Promoes': 'Promoções',
    'promoes': 'promoções',
    'Etiquetas': 'Etiquetas',
    'Codigo': 'Código',
    'codigo': 'código',
    'Codigos': 'Códigos',
    'codigos': 'códigos',
    'Numero': 'Número',
    'numero': 'número',
    'Numeros': 'Números',
    'numeros': 'números',
    'Unico': 'Único',
    'unico': 'único',
    'Unicos': 'Únicos',
    'unicos': 'únicos',
    'Vlido': 'Válido',
    'vlido': 'válido',
    'Vlidos': 'Válidos',
    'vlidos': 'válidos',
    'Invlido': 'Inválido',
    'invlido': 'inválido',
    'Invlidos': 'Inválidos',
    'invlidos': 'inválidos',
    'Obrigatrio': 'Obrigatório',
    'obrigatrio': 'obrigatório',
    'Necessrio': 'Necessário',
    'necessrio': 'necessário',
    'Disponvel': 'Disponível',
    'disponvel': 'disponível',
    'Indisponvel': 'Indisponível',
    'indisponvel': 'indisponível',
    'Possvel': 'Possível',
    'possvel': 'possível',
    'Impossvel': 'Impossível',
    'impossvel': 'impossível',
    'Visvel': 'Visível',
    'visvel': 'visível',
    'Invisvel': 'Invisível',
    'invisvel': 'invisível',
    'Acessvel': 'Acessível',
    'acessvel': 'acessível',
    'Compatvel': 'Compatível',
    'compatvel': 'compatível',
    'Responsvel': 'Responsável',
    'responsvel': 'responsável',
    'Varivel': 'Variável',
    'varivel': 'variável',
    'Variveis': 'Variáveis',
    'variveis': 'variáveis',
    'Padro': 'Padrão',
    'padro': 'padrão',
    'Padres': 'Padrões',
    'padres': 'padrões',
    'Boto': 'Botão',
    'boto': 'botão',
    'Botes': 'Botões',
    'botes': 'botões',
    'Ttulo': 'Título',
    'ttulo': 'título',
    'Ttulos': 'Títulos',
    'ttulos': 'títulos',
    'Contedo': 'Conteúdo',
    'contedo': 'conteúdo',
    'Contedos': 'Conteúdos',
    'contedos': 'conteúdos',
    'Tamanho': 'Tamanho',
    'Comrcio': 'Comércio',
    'comrcio': 'comércio',
    'Negcio': 'Negócio',
    'negcio': 'negócio',
    'Negcios': 'Negócios',
    'negcios': 'negócios',
    'Servio': 'Serviço',
    'servio': 'serviço',
    'Servios': 'Serviços',
    'servios': 'serviços',
    'Horrio': 'Horário',
    'horrio': 'horário',
    'Horrios': 'Horários',
    'horrios': 'horários',
    'Perodo': 'Período',
    'perodo': 'período',
    'Perodos': 'Períodos',
    'perodos': 'períodos',
    'Relatorio': 'Relatório',
    'relatorio': 'relatório',
    'Relatorios': 'Relatórios',
    'relatorios': 'relatórios',
    'Relatrio': 'Relatório',
    'relatrio': 'relatório',
    'Relatrios': 'Relatórios',
    'relatrios': 'relatórios',
    'Grfico': 'Gráfico',
    'grfico': 'gráfico',
    'Grficos': 'Gráficos',
    'grficos': 'gráficos',
    'Estatsticas': 'Estatísticas',
    'estatsticas': 'estatísticas',
    'Estatstica': 'Estatística',
    'estatstica': 'estatística',
    'Anlise': 'Análise',
    'anlise': 'análise',
    'Anlises': 'Análises',
    'anlises': 'análises',
    'Tendncia': 'Tendência',
    'tendncia': 'tendência',
    'Tendncias': 'Tendências',
    'tendncias': 'tendências',
    'Mdia': 'Média',
    'mdia': 'média',
    'Mdio': 'Médio',
    'mdio': 'médio',
    'Mximo': 'Máximo',
    'mximo': 'máximo',
    'Mnimo': 'Mínimo',
    'mnimo': 'mínimo',
    'Mtodo': 'Método',
    'mtodo': 'método',
    'Mtodos': 'Métodos',
    'mtodos': 'métodos',
    'Tcnico': 'Técnico',
    'tcnico': 'técnico',
    'Tcnica': 'Técnica',
    'tcnica': 'técnica',
    'Automtico': 'Automático',
    'automtico': 'automático',
    'Automtica': 'Automática',
    'automtica': 'automática',
    'Dinmico': 'Dinâmico',
    'dinmico': 'dinâmico',
    'Dinmica': 'Dinâmica',
    'dinmica': 'dinâmica',
    'Eletrnico': 'Eletrônico',
    'eletrnico': 'eletrônico',
    'Eletrnica': 'Eletrônica',
    'eletrnica': 'eletrônica',
    'Eletrnicos': 'Eletrônicos',
    'eletrnicos': 'eletrônicos',
    'Eletrnicas': 'Eletrônicas',
    'eletrnicas': 'eletrônicas',
    'Estratgia': 'Estratégia',
    'estratgia': 'estratégia',
    'Estratgias': 'Estratégias',
    'estratgias': 'estratégias',
    'Genrico': 'Genérico',
    'genrico': 'genérico',
    'Genrica': 'Genérica',
    'genrica': 'genérica',
    'Especfico': 'Específico',
    'especfico': 'específico',
    'Especfica': 'Específica',
    'especfica': 'específica',
    'Pblico': 'Público',
    'pblico': 'público',
    'Pblica': 'Pública',
    'pblica': 'pública',
    'Privado': 'Privado',
    'Bsico': 'Básico',
    'bsico': 'básico',
    'Bsica': 'Básica',
    'bsica': 'básica',
    'Avanado': 'Avançado',
    'avanado': 'avançado',
    'Avanada': 'Avançada',
    'avanada': 'avançada',
    'Incio': 'Início',
    'incio': 'início',
    'Trmino': 'Término',
    'trmino': 'término',
    'Referncia': 'Referência',
    'referncia': 'referência',
    'Referncias': 'Referências',
    'referncias': 'referências',
    'Experincia': 'Experiência',
    'experincia': 'experiência',
    'Experincias': 'Experiências',
    'experincias': 'experiências',
    'Frequncia': 'Frequência',
    'frequncia': 'frequência',
    'Sequncia': 'Sequência',
    'sequncia': 'sequência',
    'Presena': 'Presença',
    'presena': 'presença',
    'Ausncia': 'Ausência',
    'ausncia': 'ausência',
    'Diferena': 'Diferença',
    'diferena': 'diferença',
    'Diferenas': 'Diferenças',
    'diferenas': 'diferenças',
    'Preferncia': 'Preferência',
    'preferncia': 'preferência',
    'Preferncias': 'Preferências',
    'preferncias': 'preferências',
    'Transferncia': 'Transferência',
    'transferncia': 'transferência',
    'Transfenrcias': 'Transferências',
    'transfenrcias': 'transferências',
    'Emergncia': 'Emergência',
    'emergncia': 'emergência',
    'Urgncia': 'Urgência',
    'urgncia': 'urgência',
    'Eficincia': 'Eficiência',
    'eficincia': 'eficiência',
    'Dependncia': 'Dependência',
    'dependncia': 'dependência',
    'Independncia': 'Independência',
    'independncia': 'independência',
    'Ocorrncia': 'Ocorrência',
    'ocorrncia': 'ocorrência',
    'Ocorrncias': 'Ocorrências',
    'ocorrncias': 'ocorrências',
    'Concorrncia': 'Concorrência',
    'concorrncia': 'concorrência',
    'Existncia': 'Existência',
    'existncia': 'existência',
    'Persistncia': 'Persistência',
    'persistncia': 'persistência',
    'Consistncia': 'Consistência',
    'consistncia': 'consistência',
    'Correspondncia': 'Correspondência',
    'correspondncia': 'correspondência',
    'Excelncia': 'Excelência',
    'excelncia': 'excelência',
    'Gerncia': 'Gerência',
    'gerncia': 'gerência',
    'Agncia': 'Agência',
    'agncia': 'agência',
    'Licena': 'Licença',
    'licena': 'licença',
    'Potncia': 'Potência',
    'potncia': 'potência',
    'Distncia': 'Distância',
    'distncia': 'distância',
    'Instncia': 'Instância',
    'instncia': 'instância',
    'Substncias': 'Substâncias',
    'substncias': 'substâncias',
    'Circunstncias': 'Circunstâncias',
    'circunstncias': 'circunstâncias',
    'Tolerncia': 'Tolerância',
    'tolerncia': 'tolerância',
    'Vigilncia': 'Vigilância',
    'vigilncia': 'vigilância',
    'Relevncia': 'Relevância',
    'relevncia': 'relevância',
    'Importncia': 'Importância',
    'importncia': 'importância',
    'rea': 'Área',
    'Memria': 'Memória',
    'memria': 'memória',
    'Bateria': 'Bateria',
    'Galeria': 'Galeria',
    'Categoria': 'Categoria',
    'categoria': 'categoria',
    'Categorias': 'Categorias',
    'categorias': 'categorias',
    'Srie': 'Série',
    'srie': 'série',
    'Sries': 'Séries',
    'sries': 'séries',
    'Famlia': 'Família',
    'famlia': 'família',
    'Famlias': 'Famílias',
    'famlias': 'famílias',
    
    # ============================================
    # PALAVRAS COM CARACTERES CORROMPIDOS (tipo 1)
    # ============================================
    
    # Palavras encontradas nos arquivos
    'SugestÃµes': 'Sugestões',
    'SugestÃ£o': 'Sugestão',
    'sugestÃµes': 'sugestões',
    'sugestÃ£o': 'sugestão',
    'SuGestÃ£o': 'Sugestão',
    'suGestÃ£o': 'sugestão',
    'InformaÃ§Ã£o': 'Informação',
    'informaÃ§Ã£o': 'informação',
    'InformaÃ§Ãµes': 'Informações',
    'informaÃ§Ãµes': 'informações',
    'ReduÃ§Ã£o': 'Redução',
    'reduÃ§Ã£o': 'redução',
    'ReduÃ§Ãµes': 'Reduções',
    'reduÃ§Ãµes': 'reduções',
    'ReduÃ£Ã£es': 'Reduções',
    'AÃ§Ã£o': 'Ação',
    'aÃ§Ã£o': 'ação',
    'AÃ§Ãµes': 'Ações',
    'aÃ§Ãµes': 'ações',
    'DescriÃ§Ã£o': 'Descrição',
    'descriÃ§Ã£o': 'descrição',
    'PosiÃ§Ã£o': 'Posição',
    'posiÃ§Ã£o': 'posição',
    'ConfiguraÃ§Ã£o': 'Configuração',
    'configuraÃ§Ã£o': 'configuração',
    'ConfiguraÃ§Ãµes': 'Configurações',
    'configuraÃ§Ãµes': 'configurações',
    'SincronizaÃ§Ã£o': 'Sincronização',
    'sincronizaÃ§Ã£o': 'sincronização',
    'OperaÃ§Ã£o': 'Operação',
    'operaÃ§Ã£o': 'operação',
    'OperaÃ§Ãµes': 'Operações',
    'operaÃ§Ãµes': 'operações',
    'ExportaÃ§Ã£o': 'Exportação',
    'exportaÃ§Ã£o': 'exportação',
    
    # NOVAS PALAVRAS ADICIONADAS
    'MÃ©dio': 'Médio',
    'mÃ©dio': 'médio',
    'MÃ©dia': 'Média',
    'mÃ©dia': 'média',
    'EstatÃ­sticas': 'Estatísticas',
    'estatÃ­sticas': 'estatísticas',
    'EstatÃ­stica': 'Estatística',
    'estatÃ­stica': 'estatística',
    'TendÃªncias': 'Tendências',
    'tendÃªncias': 'tendências',
    'TendÃªncia': 'Tendência',
    'tendÃªncia': 'tendência',
    'DistribuiÃ§Ã£o': 'Distribuição',
    'distribuiÃ§Ã£o': 'distribuição',
    'RelatÃ³rio': 'Relatório',
    'relatÃ³rio': 'relatório',
    'RelatÃ³rios': 'Relatórios',
    'relatÃ³rios': 'relatórios',
    'LÃ­der': 'Líder',
    'lÃ­der': 'líder',
    'DinamÃ¢micos': 'Dinâmicos',
    'dinamÃ¢micos': 'dinâmicos',
    'DinamÃ¢mico': 'Dinâmico',
    'dinamÃ¢mico': 'dinâmico',
    'DinamÃ¢mica': 'Dinâmica',
    'dinamÃ¢mica': 'dinâmica',
    'hÃ¡': 'há',
    'HÃ¡': 'Há',
    'ImportaÃ§Ã£o': 'Importação',
    'importaÃ§Ã£o': 'importação',
    'AtualizaÃ§Ã£o': 'Atualização',
    'atualizaÃ§Ã£o': 'atualização',
    'NotificaÃ§Ã£o': 'Notificação',
    'notificaÃ§Ã£o': 'notificação',
    'NotificaÃ§Ãµes': 'Notificações',
    'notificaÃ§Ãµes': 'notificações',
    'ValidaÃ§Ã£o': 'Validação',
    'validaÃ§Ã£o': 'validação',
    'AutenticaÃ§Ã£o': 'Autenticação',
    'autenticaÃ§Ã£o': 'autenticação',
    'AutorizaÃ§Ã£o': 'Autorização',
    'autorizaÃ§Ã£o': 'autorização',
    'CriaÃ§Ã£o': 'Criação',
    'criaÃ§Ã£o': 'criação',
    'EdiÃ§Ã£o': 'Edição',
    'ediÃ§Ã£o': 'edição',
    'ExclusÃ£o': 'Exclusão',
    'exclusÃ£o': 'exclusão',
    'SeleÃ§Ã£o': 'Seleção',
    'seleÃ§Ã£o': 'seleção',
    'ConexÃ£o': 'Conexão',
    'conexÃ£o': 'conexão',
    'AplicaÃ§Ã£o': 'Aplicação',
    'aplicaÃ§Ã£o': 'aplicação',
    'VisualizaÃ§Ã£o': 'Visualização',
    'visualizaÃ§Ã£o': 'visualização',
    'OrganizaÃ§Ã£o': 'Organização',
    'organizaÃ§Ã£o': 'organização',
    'LocalizaÃ§Ã£o': 'Localização',
    'localizaÃ§Ã£o': 'localização',
    'ClassificaÃ§Ã£o': 'Classificação',
    'classificaÃ§Ã£o': 'classificação',
    
    # Palavras com ã
    'NÃ£o': 'Não',
    'nÃ£o': 'não',
    'EntÃ£o': 'Então',
    'entÃ£o': 'então',
    'SÃ£o': 'São',
    'sÃ£o': 'são',
    'EstÃ£o': 'Estão',
    'estÃ£o': 'estão',
    'SerÃ£o': 'Serão',
    'serÃ£o': 'serão',
    'TerÃ£o': 'Terão',
    'terÃ£o': 'terão',
    'FarÃ£o': 'Farão',
    'farÃ£o': 'farão',
    'IrÃ£o': 'Irão',
    'irÃ£o': 'irão',
    'PadrÃ£o': 'Padrão',
    'padrÃ£o': 'padrão',
    'MÃ£o': 'Mão',
    'mÃ£o': 'mão',
    'CoraÃ§Ã£o': 'Coração',
    'coraÃ§Ã£o': 'coração',
    'RazÃ£o': 'Razão',
    'razÃ£o': 'razão',
    'SessÃ£o': 'Sessão',
    'sessÃ£o': 'sessão',
    'VersÃ£o': 'Versão',
    'versÃ£o': 'versão',
    'DimensÃ£o': 'Dimensão',
    'dimensÃ£o': 'dimensão',
    'ExpansÃ£o': 'Expansão',
    'expansÃ£o': 'expansão',
    'ExtensÃ£o': 'Extensão',
    'extensÃ£o': 'extensão',
    'PermissÃ£o': 'Permissão',
    'permissÃ£o': 'permissão',
    'TransmissÃ£o': 'Transmissão',
    'transmissÃ£o': 'transmissão',
    'EmissÃ£o': 'Emissão',
    'emissÃ£o': 'emissão',
    'ComissÃ£o': 'Comissão',
    'comissÃ£o': 'comissão',
    'DiscussÃ£o': 'Discussão',
    'discussÃ£o': 'discussão',
    'ImpressÃ£o': 'Impressão',
    'impressÃ£o': 'impressão',
    'ExpressÃ£o': 'Expressão',
    'expressÃ£o': 'expressão',
    'ProgressÃ£o': 'Progressão',
    'progressÃ£o': 'progressão',
    
    # Palavras com é
    'PreÃ§o': 'Preço',
    'preÃ§o': 'preço',
    'PreÃ§os': 'Preços',
    'preÃ§os': 'preços',
    'ServiÃ§o': 'Serviço',
    'serviÃ§o': 'serviço',
    'ServiÃ§os': 'Serviços',
    'serviÃ§os': 'serviços',
    'EspaÃ§o': 'Espaço',
    'espaÃ§o': 'espaço',
    'EndereÃ§o': 'Endereço',
    'endereÃ§o': 'endereço',
    'ComeÃ§o': 'Começo',
    'comeÃ§o': 'começo',
    'AlmoÃ§o': 'Almoço',
    'almoÃ§o': 'almoço',
    'AvanÃ§o': 'Avanço',
    'avanÃ§o': 'avanço',
    'ReforÃ§o': 'Reforço',
    'reforÃ§o': 'reforço',
    'EsforÃ§o': 'Esforço',
    'esforÃ§o': 'esforço',
    
    # Palavras com á
    'JÃ¡': 'Já',
    'jÃ¡': 'já',
    'EstÃ¡': 'Está',
    'estÃ¡': 'está',
    'SerÃ¡': 'Será',
    'serÃ¡': 'será',
    'TerÃ¡': 'Terá',
    'terÃ¡': 'terá',
    'FarÃ¡': 'Fará',
    'farÃ¡': 'fará',
    'DarÃ¡': 'Dará',
    'darÃ¡': 'dará',
    'VocÃª': 'Você',
    'vocÃª': 'você',
    'AtÃ©': 'Até',
    'atÃ©': 'até',
    'TambÃ©m': 'Também',
    'tambÃ©m': 'também',
    'AlÃ©m': 'Além',
    'alÃ©m': 'além',
    'PorÃ©m': 'Porém',
    'porÃ©m': 'porém',
    'NinguÃ©m': 'Ninguém',
    'ninguÃ©m': 'ninguém',
    'AlguÃ©m': 'Alguém',
    'alguÃ©m': 'alguém',
    'QuÃ©m': 'Quém',
    'quÃ©m': 'quém',
    
    # Palavras com í
    'CÃ³digo': 'Código',
    'cÃ³digo': 'código',
    'CÃ³digos': 'Códigos',
    'cÃ³digos': 'códigos',
    'NÃºmero': 'Número',
    'nÃºmero': 'número',
    'NÃºmeros': 'Números',
    'nÃºmeros': 'números',
    'Ãšltimo': 'Último',
    'Ãºltimo': 'último',
    'Ãšltimos': 'Últimos',
    'Ãºltimos': 'últimos',
    'Ãšnico': 'Único',
    'Ãºnico': 'único',
    'PÃºblico': 'Público',
    'pÃºblico': 'público',
    'MÃ©todo': 'Método',
    'mÃ©todo': 'método',
    'MÃ©todos': 'Métodos',
    'mÃ©todos': 'métodos',
    'TÃ©cnico': 'Técnico',
    'tÃ©cnico': 'técnico',
    'TÃ©cnica': 'Técnica',
    'tÃ©cnica': 'técnica',
    'GrÃ¡fico': 'Gráfico',
    'grÃ¡fico': 'gráfico',
    'GrÃ¡ficos': 'Gráficos',
    'grÃ¡ficos': 'gráficos',
    'AutomÃ¡tico': 'Automático',
    'automÃ¡tico': 'automático',
    'AutomÃ¡tica': 'Automática',
    'automÃ¡tica': 'automática',
    'PrÃ¡tico': 'Prático',
    'prÃ¡tico': 'prático',
    'PrÃ¡tica': 'Prática',
    'prÃ¡tica': 'prática',
    'EstatÃ­stica': 'Estatística',
    'estatÃ­stica': 'estatística',
    'EstatÃ­sticas': 'Estatísticas',
    'estatÃ­sticas': 'estatísticas',
    'LogÃ­stica': 'Logística',
    'logÃ­stica': 'logística',
    'DiagnÃ³stico': 'Diagnóstico',
    'diagnÃ³stico': 'diagnóstico',
    'DiagnÃ³sticos': 'Diagnósticos',
    'diagnÃ³sticos': 'diagnósticos',
    'HistÃ³rico': 'Histórico',
    'histÃ³rico': 'histórico',
    'HistÃ³ricos': 'Históricos',
    'histÃ³ricos': 'históricos',
    'PerÃ­odo': 'Período',
    'perÃ­odo': 'período',
    'PerÃ­odos': 'Períodos',
    'perÃ­odos': 'períodos',
    'InÃ­cio': 'Início',
    'inÃ­cio': 'início',
    'HorÃ¡rio': 'Horário',
    'horÃ¡rio': 'horário',
    'HorÃ¡rios': 'Horários',
    'horÃ¡rios': 'horários',
    'CalendÃ¡rio': 'Calendário',
    'calendÃ¡rio': 'calendário',
    'InventÃ¡rio': 'Inventário',
    'inventÃ¡rio': 'inventário',
    'SalÃ¡rio': 'Salário',
    'salÃ¡rio': 'salário',
    'SalÃ¡rios': 'Salários',
    'salÃ¡rios': 'salários',
    'RelatÃ³rio': 'Relatório',
    'relatÃ³rio': 'relatório',
    'RelatÃ³rios': 'Relatórios',
    'relatÃ³rios': 'relatórios',
    'RepositÃ³rio': 'Repositório',
    'repositÃ³rio': 'repositório',
    'TerritÃ³rio': 'Território',
    'territÃ³rio': 'território',
    'ObrigatÃ³rio': 'Obrigatório',
    'obrigatÃ³rio': 'obrigatório',
    'NecessÃ¡rio': 'Necessário',
    'necessÃ¡rio': 'necessário',
    'VoluntÃ¡rio': 'Voluntário',
    'voluntÃ¡rio': 'voluntário',
    
    # Palavras com ó
    'PrÃ³ximo': 'Próximo',
    'prÃ³ximo': 'próximo',
    'PrÃ³xima': 'Próxima',
    'prÃ³xima': 'próxima',
    'PrÃ³ximos': 'Próximos',
    'prÃ³ximos': 'próximos',
    'MÃ³dulo': 'Módulo',
    'mÃ³dulo': 'módulo',
    'MÃ³dulos': 'Módulos',
    'mÃ³dulos': 'módulos',
    'SÃ³': 'Só',
    'sÃ³': 'só',
    'ApÃ³s': 'Após',
    'apÃ³s': 'após',
    'AtÃ©': 'Até',
    'atÃ©': 'até',
    
    # Palavras com ê
    'VocÃª': 'Você',
    'vocÃª': 'você',
    'VocÃªs': 'Vocês',
    'vocÃªs': 'vocês',
    'TrÃªs': 'Três',
    'trÃªs': 'três',
    'MÃªs': 'Mês',
    'mÃªs': 'mês',
    'FrequÃªncia': 'Frequência',
    'frequÃªncia': 'frequência',
    'ReferÃªncia': 'Referência',
    'referÃªncia': 'referência',
    'ExperiÃªncia': 'Experiência',
    'experiÃªncia': 'experiência',
    'SequÃªncia': 'Sequência',
    'sequÃªncia': 'sequência',
    'ConsciÃªncia': 'Consciência',
    'consciÃªncia': 'consciência',
    'CiÃªncia': 'Ciência',
    'ciÃªncia': 'ciência',
    'PaciÃªncia': 'Paciência',
    'paciÃªncia': 'paciência',
    'AudiÃªncia': 'Audiência',
    'audiÃªncia': 'audiência',
    'TendÃªncia': 'Tendência',
    'tendÃªncia': 'tendência',
    'EficiÃªncia': 'Eficiência',
    'eficiÃªncia': 'eficiência',
    'DeficiÃªncia': 'Deficiência',
    'deficiÃªncia': 'deficiência',
    'EmergÃªncia': 'Emergência',
    'emergÃªncia': 'emergência',
    'UrgÃªncia': 'Urgência',
    'urgÃªncia': 'urgência',
    'ExigÃªncia': 'Exigência',
    'exigÃªncia': 'exigência',
    'AgÃªncia': 'Agência',
    'agÃªncia': 'agência',
    'GerÃªncia': 'Gerência',
    'gerÃªncia': 'gerência',
    'PresidÃªncia': 'Presidência',
    'presidÃªncia': 'presidência',
    
    # Palavras com õ
    'OpÃ§Ãµes': 'Opções',
    'opÃ§Ãµes': 'opções',
    'FunÃ§Ãµes': 'Funções',
    'funÃ§Ãµes': 'funções',
    'CondiÃ§Ãµes': 'Condições',
    'condiÃ§Ãµes': 'condições',
    'InstruÃ§Ãµes': 'Instruções',
    'instruÃ§Ãµes': 'instruções',
    'SoluÃ§Ãµes': 'Soluções',
    'soluÃ§Ãµes': 'soluções',
    'QuestÃµes': 'Questões',
    'questÃµes': 'questões',
    'RegiÃµes': 'Regiões',
    'regiÃµes': 'regiões',
    'PromoÃ§Ãµes': 'Promoções',
    'promoÃ§Ãµes': 'promoções',
    'AvaÃ§Ãµes': 'Avações',
    'avaÃ§Ãµes': 'avações',
    'TransaÃ§Ãµes': 'Transações',
    'transaÃ§Ãµes': 'transações',
    'AÃ§Ãµes': 'Ações',
    'aÃ§Ãµes': 'ações',
    'RelaÃ§Ãµes': 'Relações',
    'relaÃ§Ãµes': 'relações',
    'InformaÃ§Ãµes': 'Informações',
    'informaÃ§Ãµes': 'informações',
    'AlteraÃ§Ãµes': 'Alterações',
    'alteraÃ§Ãµes': 'alterações',
    'AplicaÃ§Ãµes': 'Aplicações',
    'aplicaÃ§Ãµes': 'aplicações',
    
    # Palavras específicas encontradas
    'EletrÃ´nicas': 'Eletrônicas',
    'eletrÃ´nicas': 'eletrônicas',
    'EletrÃ´nica': 'Eletrônica',
    'eletrÃ´nica': 'eletrônica',
    'EletrÃ´nico': 'Eletrônico',
    'eletrÃ´nico': 'eletrônico',
    'EstratÃ©gias': 'Estratégias',
    'estratÃ©gias': 'estratégias',
    'EstratÃ©gia': 'Estratégia',
    'estratÃ©gia': 'estratégia',
    'CategorÃ­a': 'Categoría',
    'categorÃ­a': 'categoría',
    'CategorÃ­as': 'Categorías',
    'categorÃ­as': 'categorías',
    'Categoria': 'Categoria',
    'categoria': 'categoria',
    'Categorias': 'Categorias',
    'categorias': 'categorias',
    'ProdÃºto': 'Produto',
    'prodÃºto': 'produto',
    'ProdÃºtos': 'Produtos',
    'prodÃºtos': 'produtos',
    'UsuÃ¡rio': 'Usuário',
    'usuÃ¡rio': 'usuário',
    'UsuÃ¡rios': 'Usuários',
    'usuÃ¡rios': 'usuários',
    'FuncionÃ¡rio': 'Funcionário',
    'funcionÃ¡rio': 'funcionário',
    'FuncionÃ¡rios': 'Funcionários',
    'funcionÃ¡rios': 'funcionários',
    'ClientÃª': 'Cliente',
    'clientÃª': 'cliente',
    'ClientÃªs': 'Clientes',
    'clientÃªs': 'clientes',
    'Etiquetas': 'Etiquetas',
    'etiquetas': 'etiquetas',
    'InteligÃªnte': 'Inteligente',
    'inteligÃªnte': 'inteligente',
    'InteligÃªntes': 'Inteligentes',
    'inteligÃªntes': 'inteligentes',
    'InteligÃªncia': 'Inteligência',
    'inteligÃªncia': 'inteligência',
    'DisponÃ­vel': 'Disponível',
    'disponÃ­vel': 'disponível',
    'DisponÃ­veis': 'Disponíveis',
    'disponÃ­veis': 'disponíveis',
    'PossÃ­vel': 'Possível',
    'possÃ­vel': 'possível',
    'ImpossÃ­vel': 'Impossível',
    'impossÃ­vel': 'impossível',
    'VisÃ­vel': 'Visível',
    'visÃ­vel': 'visível',
    'InvisÃ­vel': 'Invisível',
    'invisÃ­vel': 'invisível',
    'AcessÃ­vel': 'Acessível',
    'acessÃ­vel': 'acessível',
    'CompatÃ­vel': 'Compatível',
    'compatÃ­vel': 'compatível',
    'ResponsÃ¡vel': 'Responsável',
    'responsÃ¡vel': 'responsável',
    'FavorÃ¡vel': 'Favorável',
    'favorÃ¡vel': 'favorável',
    'RazoÃ¡vel': 'Razoável',
    'razoÃ¡vel': 'razoável',
    'ConfiÃ¡vel': 'Confiável',
    'confiÃ¡vel': 'confiável',
    'VariÃ¡vel': 'Variável',
    'variÃ¡vel': 'variável',
    'VariÃ¡veis': 'Variáveis',
    'variÃ¡veis': 'variáveis',
    
    # Mais palavras comuns
    'Ãºtil': 'útil',
    'Ãštil': 'Útil',
    'fÃ¡cil': 'fácil',
    'FÃ¡cil': 'Fácil',
    'difÃ­cil': 'difícil',
    'DifÃ­cil': 'Difícil',
    'rÃ¡pido': 'rápido',
    'RÃ¡pido': 'Rápido',
    'rÃ¡pida': 'rápida',
    'RÃ¡pida': 'Rápida',
    'vÃ¡lido': 'válido',
    'VÃ¡lido': 'Válido',
    'vÃ¡lida': 'válida',
    'VÃ¡lida': 'Válida',
    'invÃ¡lido': 'inválido',
    'InvÃ¡lido': 'Inválido',
    'mÃ­nimo': 'mínimo',
    'MÃ­nimo': 'Mínimo',
    'mÃ¡ximo': 'máximo',
    'MÃ¡ximo': 'Máximo',
    'bÃ¡sico': 'básico',
    'BÃ¡sico': 'Básico',
    'clÃ¡ssico': 'clássico',
    'ClÃ¡ssico': 'Clássico',
    'especÃ­fico': 'específico',
    'EspecÃ­fico': 'Específico',
    'genÃ©rico': 'genérico',
    'GenÃ©rico': 'Genérico',
    'dinÃ¢mico': 'dinâmico',
    'DinÃ¢mico': 'Dinâmico',
    'dinÃ¢mica': 'dinâmica',
    'DinÃ¢mica': 'Dinâmica',
    
    # Verbos comuns
    'estÃ¡': 'está',
    'EstÃ¡': 'Está',
    'serÃ¡': 'será',
    'SerÃ¡': 'Será',
    'terÃ¡': 'terá',
    'TerÃ¡': 'Terá',
    'farÃ¡': 'fará',
    'FarÃ¡': 'Fará',
    'darÃ¡': 'dará',
    'DarÃ¡': 'Dará',
    'irÃ¡': 'irá',
    'IrÃ¡': 'Irá',
    'poderÃ¡': 'poderá',
    'PoderÃ¡': 'Poderá',
    'deverÃ¡': 'deverá',
    'DeverÃ¡': 'Deverá',
    'ficarÃ¡': 'ficará',
    'FicarÃ¡': 'Ficará',
    'chegarÃ¡': 'chegará',
    'ChegarÃ¡': 'Chegará',
    'continuarÃ¡': 'continuará',
    'ContinuarÃ¡': 'Continuará',
    'acontecerÃ¡': 'acontecerá',
    'AcontecerÃ¡': 'Acontecerá',
    'permanecerÃ¡': 'permanecerá',
    'PermanecerÃ¡': 'Permanecerá',
    
    # Palavras com PREÇO (maiúsculo em contextos de UI)
    'PREÃ‡O': 'PREÇO',
    
    # Outras palavras comuns
    'mÃ©dia': 'média',
    'MÃ©dia': 'Média',
    'sÃ©rie': 'série',
    'SÃ©rie': 'Série',
    'famÃ­lia': 'família',
    'FamÃ­lia': 'Família',
    'memÃ³ria': 'memória',
    'MemÃ³ria': 'Memória',
    'histÃ³ria': 'história',
    'HistÃ³ria': 'História',
    'categÃ³ria': 'categoria',
    'CategÃ³ria': 'Categoria',
    'galÃ©ria': 'galeria',
    'GalÃ©ria': 'Galeria',
    'batÃ©ria': 'bateria',
    'BatÃ©ria': 'Bateria',
    'Ã¡rea': 'área',
    'Ã¡rea': 'Área',
    'idÃ©ia': 'idéia',
    'IdÃ©ia': 'Idéia',
    
    # Caracteres especiais isolados
    'Â£': '£',
    'Â©': '©',
    'Â®': '®',
}

def fix_files():
    print("=" * 60)
    print("  CORRETOR DE PALAVRAS COM ENCODING CORROMPIDO")
    print("=" * 60)
    print()
    
    print("[INFO] Iniciando busca de arquivos...")
    path = Path(SEARCH_PATH)
    dart_files = list(path.rglob("*.dart"))
    
    print(f"[INFO] Encontrados {len(dart_files)} arquivos .dart")
    print(f"[INFO] Total de palavras no dicionário: {len(PALAVRAS)}")
    print()
    
    total_correcoes = 0
    arquivos_modificados = 0
    
    for i, file_path in enumerate(dart_files, 1):
        relative = str(file_path).replace(SEARCH_PATH, "").lstrip("\\")
        
        # Log de progresso a cada 50 arquivos
        if i % 50 == 0:
            print(f"[PROGRESSO] {i}/{len(dart_files)} arquivos processados...")
        
        try:
            print(f"[DEBUG] Lendo arquivo {i}/{len(dart_files)}: {relative[:50]}...")
            
            # Tentar ler com diferentes encodings
            content = None
            for enc in ['utf-8', 'utf-8-sig', 'latin-1', 'cp1252']:
                try:
                    with open(file_path, 'r', encoding=enc) as f:
                        content = f.read()
                    break
                except:
                    continue
            
            if content is None:
                print(f"[AVISO] Não foi possível ler: {relative}")
                continue
            
            original = content
            correcoes_arquivo = 0
            
            # Substituir palavras APENAS em strings e comentários
            # Evitar substituir código (variáveis, métodos, etc.)
            for errada, correta in PALAVRAS.items():
                if errada in content:
                    # Substituir apenas em strings entre aspas
                    import re
                    
                    # Padrão para strings entre aspas simples e duplas
                    patterns = [
                        # Strings com aspas simples: 'texto aqui'
                        r"'([^']*" + re.escape(errada) + r"[^']*)'",
                        # Strings com aspas duplas: "texto aqui"  
                        r'"([^"]*' + re.escape(errada) + r'[^"]*)"',
                        # Comentários de linha: // comentário
                        r'//(.*)' + re.escape(errada) + r'(.*)',
                        # Comentários de bloco: /* comentário */
                        r'/\*(.*?)' + re.escape(errada) + r'(.*?)\*/',
                        # Comentários de documentação: /// comentário
                        r'///(.*)' + re.escape(errada) + r'(.*)',
                    ]
                    
                    for pattern in patterns:
                        def replace_in_match(match):
                            full_match = match.group(0)
                            if errada in full_match:
                                # Só substitui se for palavra inteira
                                if re.search(r'\b' + re.escape(errada) + r'\b', full_match):
                                    return full_match.replace(errada, correta)
                            return full_match
                        
                        new_content = re.sub(pattern, replace_in_match, content, flags=re.DOTALL)
                        if new_content != content:
                            count = content.count(errada) - new_content.count(errada)
                            correcoes_arquivo += count
                            content = new_content
            
            if content != original:
                print(f"[INFO] Salvando {relative} com {correcoes_arquivo} correções...")
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                
                print(f"  [OK] {relative} - {correcoes_arquivo} correções")
                total_correcoes += correcoes_arquivo
                arquivos_modificados += 1
                
        except Exception as e:
            print(f"  [ERRO] {file_path}: {e}")
    
    print()
    print("=" * 60)
    print(f"  CONCLUÍDO!")
    print(f"  Arquivos modificados: {arquivos_modificados}")
    print(f"  Total de correções: {total_correcoes}")
    print("=" * 60)

if __name__ == "__main__":
    fix_files()
